config/routes.rb
Rails.application.routes.draw do

  get 'pages/term'
  resources :maintenances
  resources :materials
  resources :cities
  resources :engines

  devise_for :users

 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/engine.rb
  class Engine < ApplicationRecord
    enum engine_type: { 'Motor a reacción' => 'motor_a_reaccion', 'Motor turbohélice' => 'motor_turbohelice' }
    has_many :maintenances
    has_one_attached :photo
    validates :engine_type, presence: true
    validates :description, presence: true
    validates :name, presence: true, uniqueness: true, format: { with: /\A(REAC|TURBO)-\d+\z/ }
  
    before_create :set_default_photo
  
    private
  
    def set_default_photo
      unless self.photo.attached?
        default_photo_path = Rails.root.join('app', 'assets', 'images', 'default_engine.jpg')
        self.photo.attach(io: File.open(default_photo_path), filename: 'default_engine.jpg', content_type: 'image/jpeg')
      end
    end
  end
  

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /engines or /engines.json
  def index
    @engines = Engine.all
  end

  # GET /engines/1 or /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines or /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to engine_url(@engine), notice: "Engine was successfully created." }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1 or /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to engine_url(@engine), notice: "Engine was successfully updated." }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1 or /engines/1.json
  def destroy
    @engine.destroy

    respond_to do |format|
      format.html { redirect_to engines_url, notice: "Engine was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def generate_name
    engine_type = params[:engine_type]
    last_number = Engine.where(engine_type: engine_type).maximum(:name)
  
    if last_number.nil?
      name = "#{engine_type.upcase}-1"
    else
      last_number = last_number.split('-').last.to_i
      name = "#{engine_type.upcase}-#{last_number + 1}"
    end
  
    render json: { name: name }
  end
  


 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def engine_params
      params.require(:engine).permit(:engine_type, :name, :description, :photo)
    end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_engine.html.erb
<div id="<%= dom_id engine %>">
  <p>
    <strong>Engine type:</strong>
    <%= engine.engine_type %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= engine.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= engine.description %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= engine.photo %>
  </p>

</div>

app/views/engines/_form.html.erb
<%= form_for @engine do |f| %>
  <div class="form-group">
    <%= f.label :engine_type, 'Tipo de Motor' %>
    <%= f.select :engine_type, Engine.engine_types.keys, {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Descripción' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :photo, 'Foto del Motor' %>
    <%= f.file_field :photo, class: 'form-control' %>
  </div>
  <%= f.submit 'Guardar', class: 'btn btn-primary' %>
<% end %>

app/views/engines/edit.html.erb
<h1>Editing engine</h1>

<%= render "form", engine: @engine %>

<br>

<div>
  <%= link_to "Show this engine", @engine %> |
  <%= link_to "Back to engines", engines_path %>
</div>

app/views/engines/index.html.erb
<div class="container">
  <h1 class="mt-4">Listado de Motores</h1>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Tipo de Motor</th>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Foto</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @engines.each do |engine| %>
        <tr>
          <td><%= engine.engine_type %></td>
          <td><%= engine.name %></td>
          <td><%= engine.description %></td>
          <td><%= image_tag(engine.photo.url, class: 'img-thumbnail') if engine.photo.present? %></td>
          <td>
            <%= link_to 'Mostrar', engine, class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Editar', edit_engine_path(engine), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Eliminar', engine, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%# <%= link_to 'Nuevo Motor', new_engine_path, class: 'btn btn-success' %> 
</div>

app/views/engines/new.html.erb
<h1>New engine</h1>

<%= render "form", engine: @engine %>

<br>

<div>
  <%= link_to "Back to engines", engines_path %>
</div>

app/views/engines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @engine %>

<div>
  <%= link_to "Edit this engine", edit_engine_path(@engine) %> |
  <%= link_to "Back to engines", engines_path %>

  <%= button_to "Destroy this engine", @engine, method: :delete %>
</div>