config/routes.rb
Rails.application.routes.draw do

  get 'pages/term'
  resources :maintenances
  resources :materials
  resources :cities
  resources :engines

  devise_for :users

 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Mi Aplicación</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Inicio", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Ciudades", cities_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Motores", engines_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Mantenciones", maintenances_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Materiales", materials_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Términos y Condiciones", pages_term_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          <% if user_signed_in? %> 
            <%= current_user.role %>    
          <% else %>
            Dale registrate o conectate 
          <% end %>
        </a>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li>
              <%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
            </li>
            <li>
              <%= link_to 'Editar Perfil', edit_user_registration_path, class: 'dropdown-item' %>
            </li>
          <% else %> 
            <li>
              <%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item' %>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item' %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</nav>