config/routes.rb
Rails.application.routes.draw do

  get 'pages/term'
  resources :maintenances
  resources :materials
  resources :cities
  resources :engines

  devise_for :users

 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/city.rb
  class City < ApplicationRecord

   has_many :maintenances
  
  end
  

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <p>
    <strong>Name:</strong>
    <%= city.name %>
  </p>

</div>

app/views/cities/_form.html.erb
<%= form_with(model: city, class: 'mt-3') do |form| %>
  <% if city.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit "Actualizar Ciudad", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<div class="container mt-5">
  <h1 class="text-center">Editar Ciudad</h1>

  <div class="card">
    <div class="card-body">
      <%= render "form", city: @city %>
    </div>
  </div>

  <div class="mt-3">
    <%= link_to "Ver Ciudad", @city, class: "btn btn-primary" %> |
    <%= link_to "Regresar", cities_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/cities/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">Ciudades</h1>

  <ul class="list-group">
    <% @cities.each do |city| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= city.name %>
        <%= link_to "Edición", city, class: "btn btn-primary btn-sm" %>
      </li>
    <% end %>
  </ul>

  <div class="text-center mt-3">
    <%= link_to "Nueva Ciudad", new_city_path, class: "btn btn-success" %>
  </div>
</div>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/show.html.erb
<div class="container mt-5">
  <p class="alert alert-success"><%= notice %></p>

  <h1 class="text-center">Detalles</h1>

  <div class="card">
    <div class="card-body">
      <%= render @city %>
    </div>
  </div>

  <div class="mt-4  ">
    <%= link_to "Editar Ciudad", edit_city_path(@city), class: "btn btn-primary" %> |
    <%= link_to "Regresar", cities_path, class: "btn btn-secondary" %>
 </div>
 <div class="mt-4  ">
    <%= button_to "Eliminar Ciudad", @city, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>