config/routes.rb
Rails.application.routes.draw do

  get 'pages/term'
  resources :maintenances
  resources :materials
  resources :cities
  resources :engines

  devise_for :users

 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/material.rb
class Material < ApplicationRecord
    validates :name, presence: true
    has_and_belongs_to_many :maintenances
  end
  

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /materials or /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1 or /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials or /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to material_url(@material), notice: "Material was successfully created." }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1 or /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to material_url(@material), notice: "Material was successfully updated." }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1 or /materials/1.json
  def destroy
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_url, notice: "Material was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def material_params
      params.require(:material).permit(:name)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for @material do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nombre del Material' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit 'Guardar', class: 'btn btn-primary' %>
<% end %>

app/views/materials/_material.html.erb
<div id="<%= dom_id material %>">
  <p>
    <strong>Name:</strong>
    <%= material.name %>
  </p>

</div>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render "form", material: @material %>

<br>

<div>
  <%= link_to "Show this material", @material %> |
  <%= link_to "Back to materials", materials_path %>
</div>

app/views/materials/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Materiales</h1>

<div id="materials">
  <ul class="list-group">
    <% @materials.each do |material| %>
      <li class="list-group-item">
        <%= render material %>
        <%= link_to "Show this material", material, class: "btn btn-primary btn-sm float-right" %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "Nuevo Materiales", new_material_path, class: "btn btn-success" %>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render "form", material: @material %>

<br>

<div>
  <%= link_to "Back to materials", materials_path %>
</div>

app/views/materials/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @material %>

<div>
  <%= link_to "Edit this material", edit_material_path(@material) %> |
  <%= link_to "Back to materials", materials_path %>

  <%= button_to "Destroy this material", @material, method: :delete %>
</div>